port: 7470

docker:
  network: cortical-net
  workspace_root: /workspaces
  workspace_host_root: ${WORKSPACE_HOST_ROOT}
  credentials_host_path: ${CREDENTIALS_HOST_PATH}
  sleeve_image: protectorate-sleeve:latest

poll_interval: 1h
idle_threshold: 0s
max_sleeves: 10
